/**
 * Any client-server message should fit this structure
 *
 * @template MessagePayload - what kind of data passed with the message
 */
export interface Message<MessagePayload> {
  /**
   * Unique identifier of a message.
   * Uses nanoid(10).
   *
   * In case of ResponseMessage, there will be an id of a message to respond
   * In case of NewMessage, there will be an unique id
   */
  messageId: string;

  /**
   * Any payload like workspaces and etc.
   */
  payload: MessagePayload;
}

/**
 * Message sent in response to another message
 * Contains 'messageId' of the message to reply and the 'payload'
 * Does not contain 'type'
 */
export interface ResponseMessage<MessagePayload> extends Message<MessagePayload> {
}

/**
 * Message generated by Client or an API
 * Contains the 'type' field
 */
export interface NewMessage<MessagePayload> extends Message<MessagePayload> {
  /**
   * Message type definition,
   * for example 'authorize' or 'update-workspace'
   */
  type: string;
}

/**
 * Any client-server file transport message should fit this structure
 *
 * @template MessagePayload - what kind of data passed with the file transport message
 */
export interface FileTransferMessage<MessagePayload> {
  /**
   * File id
   */
  fileId: string;

  /**
   * Any payload like workspaces and etc.
   */
  payload: MessagePayload;
}

/**
 * Message sent in response to another file transport chunk
 * Contains 'fileId' of the message to reply, 'isUploaded' - is file fully uploaded on the server side,
 * 'chunkNumber' - number of uploaded chunk and the 'payload'
 * Does not contain 'type'
 */
export interface FileTransferResponseMessage<MessagePayload> extends FileTransferMessage<MessagePayload> {
  /**
   * Is file fully uploaded.
   */
  isUploaded: boolean;

  /**
   * Number of uploaded chunk
   */
  chunkNumber: number;
}

/**
 * File Transport Message generated by Client or an API
 * Contains the 'type' and 'file' field
 */
export interface NewFileTransferMessage<MessagePayload> extends FileTransferMessage<MessagePayload> {
  /**
   * Type of file transport request
   */
  type: string;

  /**
   * File data
   */
  file: Buffer;
}
